StoreFrontSchema.UI.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StoreFrontSchema.UI.MVC.Models;
using System.Diagnostics;

namespace StoreFrontSchema.UI.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StoreFrontSchema.UI.MVC/Controllers/WeaponsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StoreFrontSchema.DATA.EF.Models;
using StoreFrontSchema.UI.MVC.Utilities;
using X.PagedList;

namespace StoreFrontSchema.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WeaponsController : Controller
    {
        private readonly StoreFrontSchemaContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;


        public WeaponsController(StoreFrontSchemaContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Weapons
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var storeFrontSchemaContext = _context.Weapons.Include(w => w.Category).Include(w => w.Smith);
            return View(await storeFrontSchemaContext.ToListAsync());
        }

        #region Implementing Paged List

        //1) Install package for X.PagedList.Mvc.Core
        //      - Open Package Manger Console -> select the UI project -> install-package x.pagedlist.mvc.core
        //2) Add using statements and update model declaration in the View
        //3) Add using statement to Controller
        //4) Add param to Controller Action
        //5) Add page size variable in Action
        //6) Update return statement in Controller Action
        //7) Add Counter in View
        // 8) Create a new CSS file in wwwroot/css named 'PagedList.css'
        //      - NOTE: We may need to go to the package's NuGet page and copy the CSS directly
        //      - X.PagedList CSS file link (go here to copy the code):https://github.com/dncuug/X.PagedList/blob/master/examples/Example.Website/wwwroot/css/PagedList.css
        // 9) Add a <link> to the _Layout referencing 'PagedList.css'

        #endregion

        [AllowAnonymous]
        public async Task<IActionResult> TiledWeapons(string searchTerm, int categoryId = 0, int page = 1)
        {
            //if (User.IsInRole("Admin"))
            //{
            //    var weapons = _context.Weapons
            //    .Include(w => w.Category)
            //    .Include(w => w.Smith)
            //    .Include(w => w.OrderProducts);
            //    return View(await weapons.ToListAsync());
            //}
            //else
            //{
            //    var weapons = _context.Weapons.Where(w => w.IsDiscontinued == false && w.InStock > 0)
            //    .Include(w => w.Category)
            //    .Include(w => w.Smith)
            //    .Include(w => w.OrderProducts);
            //    return View(await weapons.ToListAsync());

            //}
            int pageSize = 6;


            var weapons = _context.Weapons.Where(p => !p.IsDiscontinued)
               .Include(p => p.Category)
               .Include(p => p.Smith)
               .Include(p => p.OrderProducts).ToList();

            #region Optional Category Filter

            //Create a ViewData object to send a list of categories to View. This is the same as we see in products/create 4/20/23

            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");


            //Create a ViewBag variable to persist selected category
            ViewBag.Category = 0;

            if (categoryId != 0)
            {
                weapons = weapons.Where(p => p.CategoryId == categoryId).ToList();

                //Repopulate the dropdown with current category selected.
                ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", categoryId);

                ViewBag.Category = categoryId;

            }

            #endregion



            #region Optional Search Filter

            if (!String.IsNullOrEmpty(searchTerm))
            {
                weapons = weapons.Where(p =>
                    p.ProductName.ToLower().Contains(searchTerm.ToLower()) ||
                    p.Smith.SmithName.ToLower().Contains(searchTerm.ToLower()) ||
                    p.Category.CategoryName.ToLower().Contains(searchTerm.ToLower()) ||
                    p.ProductDescription.ToLower().Contains(searchTerm.ToLower())).ToList();

                //ViewBag for the total number of results
                ViewBag.NbrResults = weapons.Count;

                //ViewBag for search term
                ViewBag.SearchTerm = searchTerm;

            }
            else
            {
                ViewBag.NbrResults = null;
                ViewBag.SearchTerm = null;
            }

            #endregion

            //return View(weapons);
            return View(weapons.ToPagedList(page, pageSize));

        }

        // GET: Weapons/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Weapons == null)
            {
                return NotFound();
            }

            var weapon = await _context.Weapons
                .Include(w => w.Category)
                .Include(w => w.Smith)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (weapon == null)
            {
                return NotFound();
            }

            return View(weapon);
        }

        // GET: Weapons/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewData["SmithId"] = new SelectList(_context.Vendors, "SmithId", "SmithName");
            return View();
        }

        // POST: Weapons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductPrice,ProductDescription,InStock,BackOrder,IsDiscontinued,CategoryId,SmithId,ProductImage,ImageFile")] Weapon weapon)
        {
            if (ModelState.IsValid)
            {
                #region File Upload - Create w/Image Utility
                if (weapon.ImageFile != null)
                {
                    // process the file

                    //check the file type
                    // - retrieve extension of file
                    string ext = Path.GetExtension(weapon.ImageFile.FileName);

                    // - Create a list of valid extensions
                    string[] validExts = { ".jpg", ".jpeg", ".gif", ".png" };

                    // - Check the extension versus list of valid extensions
                    if (validExts.Contains(ext.ToLower()) && weapon.ImageFile.Length < 4_194_303)
                    {
                        // Generate unique file name
                        weapon.ProductImage = Guid.NewGuid() + ext;

                        //Save to web server(here its wwwroot/images)
                        // - retrieve the path to web root
                        string webRootPath = _webHostEnvironment.WebRootPath;

                        // - Create a variable for image path
                        string fullImagePath = webRootPath + "/images/";

                        //Create a memory stream to read the image into the web server memory
                        using (var memoryStream = new MemoryStream())
                        {
                            await weapon.ImageFile.CopyToAsync(memoryStream);
                            using (var img = Image.FromStream(memoryStream))
                            {
                                // Now , send the img to ImageUtiltiy to be resized and saved
                                //Need 5 args for this to resize our image
                                //1- int max img size
                                //2- int max thumbnail
                                //3-string full path where file will be saved
                                //4-(Image) an image
                                //5-(string) filename

                                int maxImageSize = 500;
                                int maxThumbSize = 100;

                                ImageUtility.ResizeImage(fullImagePath, weapon.ProductImage, img, maxImageSize, maxThumbSize);
                            }
                        }
                    }

                }
                else
                {
                    // assign a default image
                    // IF no image uploaded, assing default file name
                    //Will also need to DL default image and name it "noImage.png" place it in wwwroot/images.
                    weapon.ProductImage = "noImage.jpg";
                }
                #endregion

                _context.Add(weapon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(TiledWeapons));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", weapon.CategoryId);
            ViewData["SmithId"] = new SelectList(_context.Vendors, "SmithId", "SmithName", weapon.SmithId);
            return View(weapon);
        }

        // GET: Weapons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Weapons == null)
            {
                return NotFound();
            }

            var weapon = await _context.Weapons.FindAsync(id);
            if (weapon == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", weapon.CategoryId);

StoreFrontSchema.UI.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- cycle section start -->
<div class="cycle_section layout_padding">
    <div class="container">
        <h1 class="cycle_taital">Our Weapons</h1>
        <p class="cycle_text">We carry a variety of implements from the traditional in hand-to-hand combat to more exotic and mass casualty inducing technologies.</p>
        <div class="cycle_section_2 layout_padding">
            <div class="row">
                <div class="col-md-6">
                    <div class="box_main">
                        <h6 class="number_text">01</h6>
                        <div class="image_2"><img src="~/images/dao.jpg"></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h1 class="cycles_text">Jian</h1>
                    <p class="lorem_text">Some call it "The Gentleman of Weapons". A multipurpose cut and thrust weapon capable of stabbing, as well as making both precise cuts and slashes.</p>
                    <div class="btn_main">
                        <div class="buy_bt"><a asp-action ="TiledWeapons" asp-controller="Weapons">View Now</a></div>
                        <h4 class="price_text">Price <span style=" color: #f7c17b">$</span> <span style=" color: #325662">200</span></h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="cycle_section_3 layout_padding">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="cycles_text">War Hammer</h1>
                    <p class="lorem_text">An armored defenders worst nightmare. Able to make deadly dents in armor and cause bone shattering injuries.</p>
                    <div class="btn_main">
                        <div class="buy_bt"><a asp-action="TiledWeapons" asp-controller="Weapons">View Now</a></div>
                        <h4 class="price_text">Price <span style=" color: #f7c17b">$</span> <span style=" color: #325662">150</span></h4>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box_main_3">
                        <h6 class="number_text_2">02</h6>
                        <div class="image_2"><img src="~/images/warhammer.jpg"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cycle_section_2 layout_padding">
            <div class="row">
                <div class="col-md-6">
                    <div class="box_main_3">
                        <h6 class="number_text_2">03</h6>
                        <div class="image_2"><img src="~/images/kunai.jpg"></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h1 class="cycles_text">Assassin's <br>Kunai</h1>
                    <p class="lorem_text">Perfect for concealment! Primarily used as tools but, when used as a weapon it makes a useful stabbing and thrusting implement.</p>
                    <div class="btn_main">
                        <div class="buy_bt"><a asp-action="TiledWeapons" asp-controller="Weapons">View Now</a></div>
                        <h4 class="price_text">Price <span style=" color: #f7c17b">$</span> <span style=" color: #325662">50</span></h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="read_btn_main">
            <div class="read_bt"><a href="#">Read More</a></div>
        </div>
    </div>
</div>
<!-- cycle section end -->
<!-- about section start -->
<div class="about_section layout_padding">
    <div class="container">
        <h1 class="about_taital">About Our Weapons Store</h1>
        <p class="about_text">
            “We provide and deliver weapons technology that solves age old problems in a beautifully simplistic or sometimes advanced method.”


        </p>
        <div class="about_main">
            <img src="~/images/crossedsabers.jpg" class="image_5">
        </div>
        <div class="read_bt_1"><a href="#">Read More</a></div>
    </div>
</div>
<!-- about section end -->
<!-- client section start -->
<div class="client_section layout_padding">
    <div id="my_slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <div class="client_main">
                        <h1 class="client_taital">Customer Feedback</h1>
                        <div class="client_section_2">
                            <div class="client_left">
                                <div><img src="~/images/warrior.jpg" class="client_img"></div>
                            </div>
                            <div class="client_right">
                                <div class="quote_icon"><img src="~/images/quote-icon.png"></div>
                                <p class="client_text">"My swords would always crack during battle, but now with my new broadsword from WeaponTech I've cleaved five men in two in the last week!"</p>
                                <h3 class="client_name">Hrothgar Skullcleaver</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="client_main">
                        <h1 class="client_taital">Customer Feedback</h1>
                        <div class="client_section_2">
                            <div class="client_left">
                                <div><img src="~/images/viking.jpg" class="client_img"></div>
                            </div>
                            <div class="client_right">
                                <div class="quote_icon"><img src="~/images/quote-icon.png"></div>
                                <p class="client_text">"When I'm in a berserker rage the last thing I want to think about is my weapon failing. With WeaponTech products I'm free to focus on hearing the lamentation of my enemies."</p>
                                <h3 class="client_name">Ivar Svartsson</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="client_main">
                        <h1 class="client_taital">Customer Feedback</h1>
                        <div class="client_section_2">
                            <div class="client_left">
                                <div><img src="~/images/bhninja.jpg" class="client_img"></div>
                            </div>
                            <div class="client_right">
                                <div class="quote_icon"><img src="~/images/quote-icon.png"></div>
                                <p class="client_text">“The blackness of my belt is like the inside of a coffin on a moonless night...thanks to WeaponTech”</p>
                                <h3 class="client_name">Haru</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
        </a>
        <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
</div>
<!-- client section end -->
<!-- news section start -->
<div class="news_section layout_padding">
    <div class="container">
        <h1 class="news_taital">News</h1>
        <p class="news_text">Check out our articles about new trends and topics impacting the industry.</p>
        <div class="news_section_2 layout_padding">
            <div class="row">
                <div class="col-sm-4">
                    <div class="box_main_1">
                        <div class="zoomout frame"><img src="~/images/wargame.jpg"></div>
                        <div class="padding_15">
                            <h2 class="speed_text">Crusader Digest</h2>
                            <div class="post_text">Post by : Steve <span style="float: right;">2-5-2022</span></div>
                            <p class="long_text">With all of the advancements in technology, do we still need armored infantry? Check out our answer inside!</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="box_main_1">
                        <div class="zoomout frame"><img src="~/images/spacewarfare.jpg"></div>
                        <div class="padding_15">
                            <h2 class="speed_text">Asymmetrical Space Warfare</h2>
                            <div class="post_text">Post by : Steve <span style="float: right;">24-2-2016</span></div>
                            <p class="long_text">We take a look into recent colonial rebellions and the <em>WORLDBREAKING</em> technology being used to put a stop to it.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="box_main_1">
                        <div class="zoomout frame"><img src="~/images/swordinscabbard.jpg"></div>
                        <div class="padding_15">
                            <h2 class="speed_text">Duel Tactics</h2>
                            <div class="post_text">Post by : Steve <span style="float: right;">20-12-2019</span></div>
                            <p class="long_text">Is a Battou-jutsu stance really all it's cracked up to be? We find out!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- news section end -->
<!-- contact section start -->
<div class="contact_section layout_padding">
    <div class="container">
        <div class="contact_main">
            <h1 class="request_text">Contact Us</h1>
            <form action="/action_page.php">
                <div class="form-group">
                    <input type="text" class="email-bt" placeholder="Name" name="Name">
                </div>
                <div class="form-group">
                    <input type="text" class="email-bt" placeholder="Email" name="Name">
                </div>
                <div class="form-group">
                    <input type="text" class="email-bt" placeholder="Phone Number" name="Email">
                </div>
                <div class="form-group">
                    <textarea class="massage-bt" placeholder="Message" rows="5" id="comment" name="Message"></textarea>
                </div>
            </form>
            <div class="send_btn"><a href="#">SEND</a></div>
        </div>
    </div>
</div>
<!-- contact section end -->